/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.HorasComplementaresController;

import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dood
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    boolean tipoUsuario;
    boolean mutexAluno, mutexCoord = false;
    String idUsuario;
    

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal(boolean tipoUsuario, String idUsuario) {
        this.idUsuario=idUsuario;
        JOptionPane.showMessageDialog(null, this.idUsuario);
        initComponents();
        this.setLocationRelativeTo(null);
        this.tipoUsuario = tipoUsuario;

        if (tipoUsuario == true) {
            mutexAluno = true;
        } else {
            mutexCoord = true;
        }

        mnConCH.setVisible(mutexAluno);
        mnAluno.setVisible(mutexCoord);
        mnCertificado.setVisible(mutexAluno);
        mnRecur.setVisible(mutexAluno);
        mnRestri.setVisible(mutexCoord);
        mnConCad.setVisible(mutexCoord);
        mnValidCert.setVisible(mutexCoord);
        mnAtesConc.setVisible(mutexCoord);
        mnAlteDados.setVisible(true);

    }

    private JanelaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnAluno = new javax.swing.JMenuItem();
        mnAlteDados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnCertificado = new javax.swing.JMenuItem();
        mnRecur = new javax.swing.JMenuItem();
        mnConCH = new javax.swing.JMenuItem();
        mnRestri = new javax.swing.JMenuItem();
        mnValidCert = new javax.swing.JMenuItem();
        mnAtesConc = new javax.swing.JMenuItem();
        mnConCad = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador Acadêmico de Horas Complementares");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jDesktopPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 876, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jMenuBar1.setBorder(null);
        jMenuBar1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jMenuBar1.setOpaque(false);

        jMenu1.setText("Arquivo");

        mnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Img/door_open.png"))); // NOI18N
        mnSair.setText("Sair");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        jMenu1.add(mnSair);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Usuário");

        mnAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Img/user_add.png"))); // NOI18N
        mnAluno.setText("Confirmação de Cadastro");
        mnAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAlunoActionPerformed(evt);
            }
        });
        jMenu4.add(mnAluno);

        mnAlteDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Img/user_edit.png"))); // NOI18N
        mnAlteDados.setText("Alteração dos dados");
        mnAlteDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAlteDadosActionPerformed(evt);
            }
        });
        jMenu4.add(mnAlteDados);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Opções");

        mnCertificado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Img/page_add.png"))); // NOI18N
        mnCertificado.setText("Cadastro de Certificado");
        mnCertificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCertificadoActionPerformed(evt);
            }
        });
        jMenu2.add(mnCertificado);

        mnRecur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Img/user_comment.png"))); // NOI18N
        mnRecur.setText("Recurso de Certificado");
        mnRecur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRecurActionPerformed(evt);
            }
        });
        jMenu2.add(mnRecur);

        mnConCH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Img/application_view_columns.png"))); // NOI18N
        mnConCH.setText("Consulta de Carga Horária");
        mnConCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConCHActionPerformed(evt);
            }
        });
        jMenu2.add(mnConCH);

        mnRestri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Img/report_edit.png"))); // NOI18N
        mnRestri.setText("Restrições de Certificado");
        mnRestri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRestriActionPerformed(evt);
            }
        });
        jMenu2.add(mnRestri);

        mnValidCert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Img/accept.png"))); // NOI18N
        mnValidCert.setText("Validação de Certificado");
        mnValidCert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnValidCertActionPerformed(evt);
            }
        });
        jMenu2.add(mnValidCert);

        mnAtesConc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Img/page_go.png"))); // NOI18N
        mnAtesConc.setText("Atestado de Conclusão");
        mnAtesConc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAtesConcActionPerformed(evt);
            }
        });
        jMenu2.add(mnAtesConc);

        mnConCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Img/page_find.png"))); // NOI18N
        mnConCad.setText("Consulta de Cadastro");
        mnConCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConCadActionPerformed(evt);
            }
        });
        jMenu2.add(mnConCad);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void mnRecurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRecurActionPerformed
        IntFrmRegistroRecurso frmRegRec = new IntFrmRegistroRecurso(this.idUsuario);
        configuraInternal(frmRegRec);
    }//GEN-LAST:event_mnRecurActionPerformed

    private void configuraInternal(JInternalFrame Internal) {
        jDesktopPane.add(Internal);
        Internal.setVisible(true);
        Internal.setClosable(true);
        Internal.setResizable(false);
    }

    private void mnCertificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCertificadoActionPerformed
        IntFrmCadCertificado frmCadCer = new IntFrmCadCertificado(this.idUsuario);
        configuraInternal(frmCadCer);
    }//GEN-LAST:event_mnCertificadoActionPerformed

    private void mnAlteDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAlteDadosActionPerformed
        IntFrmEdDataAluno frmCadAlu = new IntFrmEdDataAluno(this.idUsuario);
        configuraInternal(frmCadAlu);
    }//GEN-LAST:event_mnAlteDadosActionPerformed

    private void mnConCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConCHActionPerformed
        IntFrmConsulHoras frmConHor = new IntFrmConsulHoras(this.idUsuario);
        configuraInternal(frmConHor);
    }//GEN-LAST:event_mnConCHActionPerformed

    private void mnRestriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRestriActionPerformed
        IntFrmRestrCertificado frmRestCer = new IntFrmRestrCertificado();
        configuraInternal(frmRestCer);
    }//GEN-LAST:event_mnRestriActionPerformed

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed
        new Sair().setVisible(true);
    }//GEN-LAST:event_mnSairActionPerformed

    private void mnAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAlunoActionPerformed
        IntFrmConCad frmConCad = new IntFrmConCad();
        configuraInternal(frmConCad);
    }//GEN-LAST:event_mnAlunoActionPerformed

    private void mnConCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConCadActionPerformed

        IntFrmConsCad frmConsCad = new IntFrmConsCad();
        configuraInternal(frmConsCad);
    }//GEN-LAST:event_mnConCadActionPerformed

    private void mnValidCertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnValidCertActionPerformed
        IntFrmValidaCert frmValCer = new IntFrmValidaCert();
        configuraInternal(frmValCer);
    }//GEN-LAST:event_mnValidCertActionPerformed

    private void mnAtesConcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAtesConcActionPerformed
        IntFrmEmitirAtestado frmEmAtes = new IntFrmEmitirAtestado();
        configuraInternal(frmEmAtes);
    }//GEN-LAST:event_mnAtesConcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JanelaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mnAlteDados;
    private javax.swing.JMenuItem mnAluno;
    private javax.swing.JMenuItem mnAtesConc;
    private javax.swing.JMenuItem mnCertificado;
    private javax.swing.JMenuItem mnConCH;
    private javax.swing.JMenuItem mnConCad;
    private javax.swing.JMenuItem mnRecur;
    private javax.swing.JMenuItem mnRestri;
    private javax.swing.JMenuItem mnSair;
    private javax.swing.JMenuItem mnValidCert;
    // End of variables declaration//GEN-END:variables
}
